repos:
  - repo: https://github.com/fastai/nbdev
    rev: 2.2.10
    hooks:
      - id: nbdev_clean

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-black
      - id: nbqa-isort
        args: [--profile=black, --float-to-top]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args:
          [
            --profile,
            black,
            --filter-files,
            --color,
            --balanced,
            --float-to-top,
          ]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude: \.github/workflows/diff_shades\.yml

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer

  - repo: https://github.com/iterative/dvc
    rev: 3.7.0
    hooks:
      - id: dvc-pre-commit
        additional_dependencies:
          - .[all]
        language_version: python3
        stages:
          - commit
      - id: dvc-pre-push
        additional_dependencies:
          - .[all]
        language_version: python3
        stages:
          - push
      - id: dvc-post-checkout
        additional_dependencies:
          - .[all]
        language_version: python3
        stages:
          - post-checkout
        always_run: true

  - repo: local
    hooks:
      - id: update-submodules
        name: Update Submodules
        entry: update_submodules.sh
        language: script
        stages:
          - post-checkout
