version: "3.9"
services:
  # Anchor a base service that can be extended by other services.
  elastic-nerf-base: &elastic-nerf-base
    build:
      context: .
      dockerfile: docker/elastic-nerf.Dockerfile
      args: &elastic-nerf-base-args
        CUDA_ARCHITECTURES: ${CUDA_ARCHITECTURES:-86}
        USER_ID: ${USER_ID:?}
        GROUP_ID: ${GROUP_ID:?}
        SHARED_GROUP_ID: ${SHARED_GROUP_ID}
        DOCKER_USERNAME: ${DOCKER_USERNAME:?}
        HOST_USERNAME: ${USERNAME:?}
        HOSTNAME: ${HOSTNAME:?}
        USER_WANDB_MODE: ${WANDB_MODE:-offline}
        USER_WANDB_KEY: ${WANDB_KEY:-}
        WANDB_ENTITY: ${WANDB_ENTITY:-}
        USER_HF_MODE: ${HF_MODE:-offline}
        USER_HF_TOKEN: ${HF_TOKEN:-}
        TARGET_PROJECT_DIR: ${TARGET_PROJECT_DIR:?}
        NERFSTUDIO_CACHE_DIR: /home/${DOCKER_USERNAME:?}/shared/nerfstudio

    image: ${USERNAME:?}/elastic-nerf
    user: ${USER_ID:?}:${GROUP_ID:?}
    ports:
      - ":7007"
    shm_size: 12gb
    ipc: host
    tty: true
    command: []
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # Change to ['0', '1'] to use two GPUs or specify `GPU_IDS=0,1` before running `docker compose run`
              device_ids: [ "${GPU_IDS:-0}" ]
              capabilities: [ gpu ]

  elastic-nerf-dev:
    # Add alias to base service to reuse its configuration.
    <<: *elastic-nerf-base
    build:
      context: .
      dockerfile: docker/elastic-nerf.Dockerfile
      args:
        <<: *elastic-nerf-base-args
        DEVELOPER_MODE: 1
    volumes:
      - ${HOST_WORKSPACE_PATH:-.}:${TARGET_REPO_MOUNTDIR:?}
      - ${HUGGINGFACE_CACHE_DIR:?}:/home/${DOCKER_USERNAME:?}/shared/hf_cache
      - ${NERFSTUDIO_CACHE_DIR:?}:/home/${DOCKER_USERNAME:?}/shared/nerfstudio
      - /home/${USERNAME:?}/.ssh:/home/${DOCKER_USERNAME:?}/.ssh
      - ${WANDB_CACHE_DIR:-./cache/wandb}:/home/${DOCKER_USERNAME:?}/shared/wandb_cache
      # - /home/${USERNAME:?}/.cache:/home/${DOCKER_USERNAME:?}/.cache

  elastic-nerf:
    # Add alias to base service to reuse its configuration.
    <<: *elastic-nerf-base
    build:
      context: .
      dockerfile: docker/elastic-nerf/elastic-nerf.Dockerfile
      args:
        <<: *elastic-nerf-base-args
        DEVELOPER_MODE: 0

    volumes:
      - ${HOST_WORKSPACE_PATH:-.}:${TARGET_REPO_MOUNTDIR:?}
      - ${HUGGINGFACE_CACHE_DIR:?}:/home/${DOCKER_USERNAME:?}/shared/hf_cache
      - ${NERFSTUDIO_CACHE_DIR:?}:/home/${DOCKER_USERNAME:?}/shared/nerfstudio
      - /home/${USERNAME:?}/.ssh:/home/${DOCKER_USERNAME:?}/.ssh
      - ${WANDB_CACHE_DIR:-./cache/wandb}:/home/${DOCKER_USERNAME:?}/shared/wandb_cache
