[project]
name = "elastic-nerf"
description = "Elastic Neural Radiance Fields"
channels = ["nvidia/label/cuda-11.8.0", "nvidia", "conda-forge", "pytorch"]
platforms = ["linux-64"]

[system-requirements]
libc = { family="glibc", version="2.30" }

[tasks]
# || operator in pixi allows running a command after only if the command before || fails
uv-install = "python -m pip install uv"
tcnn-install = {cmd="python -c 'import tinycudann as tcnn' || python -m uv pip install ninja --no-build-isolation git+https://github.com/NVlabs/tiny-cuda-nn/@b3473c81396fe927293bdfd5a6be32df8769927c#subdirectory=bindings/torch", depends_on=["uv-install"]}
nerfacc-install = {cmd="python -c 'import nerfacc' || python -m uv pip install --no-build-isolation git+https://github.com/nerfstudio-project/nerfacc.git", depends_on=["uv-install", "tcnn-install"]}
make-third-party-dir = {cmd="ls third-party || mkdir third-party"}
clone-hloc = {cmd="ls Hierarchical-Localization || git clone --recursive https://github.com/cvg/Hierarchical-Localization/", cwd = "third-party", depends_on=["make-third-party-dir"] }
hloc-install = {cmd="python -m uv pip install --no-build-isolation -e .", cwd = "third-party/Hierarchical-Localization" , depends_on=["clone-hloc"], outputs=["third-party/Hierarchical-Localization/hloc.egg-info/PKG-INFO"]}


nerfstudio-install = {cmd="python -c 'import nerfstudio' || python -m uv pip install nerfstudio==1.1.4", depends_on=["uv-install", "nerfacc-install"]}
post-install = {cmd="pwd", depends_on=["nerfacc-install", "tcnn-install", "hloc-install", "nerfstudio-install"]}


[dependencies]
python = ">=3.8,<3.11"
pip = ">=24.0,<25"
cuda = {version = "*", channel="nvidia/label/cuda-11.8.0"}
pytorch-cuda = {version = "11.8.*", channel="pytorch"}
pytorch = {version = ">=2.2.0,<2.3", channel="pytorch"}
torchvision = {version = ">=0.17.0,<0.18", channel="pytorch"}
pyarrow = ">=15.0.2,<15.1"
colmap = ">=3.9.1,<3.10"
numpy = "<2.0.0"
pre-commit = ">=4.0.1,<5"


[pypi-dependencies]
elastic-nerf = { path = ".", editable = true}
gonas = { path = "third-party/gonas", editable = true}
